name: mc_launch
description: "A Dart package for launching Minecraft with configurable parameters."
version: 0.1.0+2
homepage:

environment:
  sdk: ^3.8.1

dependencies:
  path: ^1.8.3

dev_dependencies:
  test: ^1.24.0
  lints: ^4.0.0
