name: mc_launch
description: "A Dart package for launching Minecraft with configurable parameters."
version: 0.0.1
homepage:

environment:
  sdk: ^3.8.1

dependencies:
  # 暂时不需要任何外部依赖

dev_dependencies:
  test: ^1.24.0
  lints: ^4.0.0
